import json

questions = {
  "2": {
    "41": {"q": "What time will the speakers leave for the meeting?", "o": ["8:00.", "6:45.", "7:30.", "11:30."]},
    "42": {"q": "How will they get to the meeting?", "o": ["Bus.", "Taxi.", "Subway.", "Private car."]},
    "43": {"q": "Where will the meeting be held?", "o": ["Downtown.", "At the hotel.", "At the office.", "At the conference center."]},
    "44": {"q": "Where does this conversation take place?", "o": ["A bank.", "An accountant's office.", "A driving school.", "An office supply store."]},
    "45": {"q": "What does the woman ask the man to give her?", "o": ["An identification card.", "A check.", "A pen.", "Cash."]},
    "46": {"q": "What does the woman ask the man to do?", "o": ["Check his license.", "Write his name.", "Read a sign.", "Pay cash."]},
    "47": {"q": "Where will the man be next week?", "o": ["Downtown.", "At a ranch.", "At the branch office.", "At the accountant's office."]},
    "48": {"q": "When will the speakers meet?", "o": ["Next week.", "The following Monday.", "The following Friday.", "Next month."]},
    "49": {"q": "What will the man do now?", "o": ["Look at his calendar.", "Call his assistant.", "Write a check.", "Go to New York."]},
    "50": {"q": "When will the budget report be ready?", "o": ["At 10:00.", "This afternoon.", "Tomorrow morning.", "On Friday."]},
    "51": {"q": "Where does the man want the woman to leave the report?", "o": ["In his office.", "In his mailbox.", "In the post office.", "In the conference room."]},
    "52": {"q": "What does the woman offer to do?", "o": ["Pass out the report at the meeting.", "Make copies of the report.", "Clean the man's desk.", "Work until 8:00."]},
    "53": {"q": "How many nights does the man want to stay at the hotel?", "o": ["1.", "2.", "3.", "4."]},
    "54": {"q": "When will the man arrive at the hotel?", "o": ["Friday.", "Saturday.", "Sunday.", "Monday."]},
    "55": {"q": "What does the woman ask the man for?", "o": ["His room number.", "His flight number.", "His reservation number.", "His credit card number."]},
    "56": {"q": "How did the man plan to travel to Toronto?", "o": ["By bus.", "By car.", "By plane.", "By train."]},
    "57": {"q": "What's the weather like?", "o": ["Rain.", "Snow.", "Hot.", "Clear."]},
    "58": {"q": "When will the weather change?", "o": ["This morning.", "This afternoon.", "Tonight.", "Tomorrow."]},
    "59": {"q": "What does the man want to do?", "o": ["Visit the park.", "Park his car.", "Buy groceries.", "Repair his car."]},
    "60": {"q": "How far does he have to go?", "o": ["1 block.", "3 blocks.", "1 mile.", "3 miles."]},
    "61": {"q": "How much will he have to pay?", "o": ["$0.", "$4.", "$8.", "$20."]},
    "62": {"q": "How does the woman feel?", "o": ["Sad.", "Bored.", "Happy.", "Angry."]},
    "63": {"q": "When will they celebrate the man's promotion?", "o": ["Now.", "Tonight.", "At 10:00.", "Next Monday."]},
    "64": {"q": "What does the woman offer to do?", "o": ["Help the man with his work.", "Prepare dinner for the man.", "Pay for the man's lunch.", "Give the man her seat."]},
    "65": {"q": "Why is the woman hosting the dinner?", "o": ["She's having a meeting.", "She's entertaining clients.", "She's having a birthday party.", "She's celebrating her retirement."]},
    "66": {"q": "How many people will be at the dinner?", "o": ["15.", "16.", "50.", "60."]},
    "67": {"q": "What food does the woman order?", "o": ["Rice", "Fish.", "Steak.", "Chicken."]},
    "68": {"q": "What does the woman want new shoes for?", "o": ["A trip.", "A party.", "A present.", "An interview."]},
    "69": {"q": "What color shoes does the woman want?", "o": ["White.", "Gray.", "Blue.", "Black."]},
    "70": {"q": "When does she need to wear them?", "o": ["Now.", "Sunday.", "Monday.", "Next month."]},
    "71": {"q": "Where would this announcement be heard?", "o": ["On a bus.", "On a plane.", "On a train.", "On a ship."]},
    "72": {"q": "When will they arrive at their destination?", "o": ["In 13 minutes.", "In 30 minutes.", "In one hour.", "In two hours."]},
    "73": {"q": "What are passengers asked to do?", "o": ["Read a schedule.", "Order drinks.", "Eat a meal.", "Sit down."]},
    "74": {"q": "What days is the dental office open?", "o": ["Tuesday and Friday only.", "Tuesday through Friday only.", "Tuesday through Saturday only", "Tuesday, Friday, and Saturday only."]},
    "75": {"q": "What should a caller do in case of emergency?", "o": ["Call another number.", "Call during office hours.", "Press 1.", "Press 2."]},
    "76": {"q": "How can a caller make an appointment?", "o": ["Speak with the dentist.", "Call back later.", "Leave a message.", "Ask for an assistant."]},
    "77": {"q": "Who is this talk for?", "o": ["Office workers.", "Police officers.", "Health experts.", "Gym teachers."]},
    "78": {"q": "How much exercise should adults get every day?", "o": ["4 to 5 minutes.", "45 minutes.", "One hour.", "Three hours."]},
    "79": {"q": "What does the speaker recommend about exercise for adults?", "o": ["They should exercise at the gym.", "They should exercise once a day.", "They should exercise in the afternoon.", "They should exercise several times a day."]},
    "80": {"q": "What kind of business is Branwell's?", "o": ["Café.", "Sports store.", "Clothing store.", "Travel agency."]},
    "81": {"q": "What size discount is offered?", "o": ["5%.", "10%.", "20%.", "25%."]},
    "82": {"q": "When does the sale begin?", "o": ["Saturday.", "Sunday.", "Monday.", "Tuesday."]},
    "83": {"q": "What kind of Service is advertised?", "o": ["Employment agency.", "Computer training.", "Office rental.", "Hotel."]},
    "84": {"q": "What fee is charged for the Service?", "o": ["$0.", "$13.", "$30.", "$35."]},
    "85": {"q": "What are listeners asked to do?", "o": ["Write a letter.", "Call the office.", "Visit the office.", "Make an appointment."]},
    "86": {"q": "What is the weather today?", "o": ["Cold.", "Wind.", "Rain.", "Snow."]},
    "87": {"q": "What problem has the weather caused?", "o": ["School closings.", "Trains delayed.", "Loss of electricity.", "Damage to bridge."]},
    "88": {"q": "When will the weather change?", "o": ["This afternoon.", "This evening.", "Tomorrow morning.", "Next week."]},
    "89": {"q": "What time will the workshops begin?", "o": ["2:00.", "10:00.", "10:15.", "12:15."]},
    "90": {"q": "Where will lunch be served?", "o": ["In the lobby.", "In the auditorium.", "On the ground floor.", "On the second floor."]},
    "91": {"q": "What will happen after lunch?", "o": ["Coffee will be served.", "There will be a discussion.", "Workshops will be held.", "Registration will end."]},
    "92": {"q": "Why is there no train Service to New York?", "o": ["The tracks are flooded.", "The train is damaged.", "There aren't enough seats.", "There isn't any heating."]},
    "93": {"q": "What are passengers asked to do?", "o": ["Speak with a ticket agent.", "Travel on another date.", "Buy another ticket.", "Take a bus."]},
    "94": {"q": "When will the trains run again?", "o": ["It is not certain.", "Later in the evening.", "At 4:00.", "At 6:30."]},
    "95": {"q": "What will be constructed?", "o": ["A park.", "A bridge.", "Some monuments.", "A new City Hall."]},
    "96": {"q": "When will construction begin?", "o": ["In the fall.", "In the winter.", "In September.", "In November."]},
    "97": {"q": "What will the mayor do tomorrow?", "o": ["Meet with the budget committee", "Give a press conference.", "Visit a museum.", "Give a speech."]},
    "98": {"q": "When will Dr. Jones talk?", "o": ["After the meeting.", "During lunch.", "Next week.", "Next month."]},
    "99": {"q": "What will Dr. Jones talk about?", "o": ["Office management.", "Public speaking.", "International relations.", "Making videos."]},
    "100": {"q": "What are the listeners asked to do?", "o": ["Attend a lunch.", "Pay with a check.", "Mark their calendars.", "Got to a press conference."]}
  }
}

with open('questions_2.json', 'w', encoding='utf-8') as f:
  json.dump(questions, f, ensure_ascii=False, indent=2)
